### ISSUE TITLE
[Setting] API 첫 연동 세팅

### ISSUE THREAD

**Issue by Chaeyeon1** [InSange/PigBrothers#3]
# 🌝Description
- 백엔드와 api 연동

<br>

# 📋To-do List

- [x] tanstack-query library 설치
- [x] swagger-api 라이브러리 설치
- [x] api 폴더 구조 설정
- [x] 백엔드 api 연동

<br>

# ⚠️ETC
