### ISSUE TITLE
[Feat] API

### ISSUE THREAD

**Issue by InSange** [InSange/PigBrothers#5]
---
name: 이슈 템플릿
about: 이슈 설명, 할일 목록, 기타 사항
title: ''
labels:
  "\U0001F41EBug, \U0001FA7BDeploy, \U0001F4D1Docs, ⭐Feature, \U0001F6E0️fix,
  ❗modify, \U0001F527Refactor, ⚙️Setting, ✅Test"
assignees: dla8156, InSange, seonna7
---

#🌝Description

- UserData 응답 모델 추가
- UserData Post, Get 설정

<br>

#📋To-do List

- [ ] UserData 반환 모델 생성
- [ ] UserData Post 추가
- [ ] UserData Post 예외 처리
- [ ] UserData Get 추가
- [ ] UserData Get 예외 처리

<br>

#⚠️ETC
